name: CrazyAuctionAddon
main: net.azisaba.crazyauctionaddon.CrazyAuctionAddon
version: 1.0.3
api-version: 1.16
author: pino223

commands:
  caa:
    description: CrazyAuctionAddon main command
    usage: /caa <set|noselllist>
    permission: crazyauctionaddon.use
    permission-message: 権限がありません

permissions:
  crazyauctionaddon.use:
    description: Allows use of /caa commands
    default: op
